cookie:
  expiry_days: 30
  key: portfolio_projects
  name: portfolio_p
credentials:
  usernames:
    iosgv:
      email: dbosnjak95va@gmail.com
      name: iosg ventures
      password: iosg2023
preauthorized:
  emails:
  - dbosnjak95va@gmail.com
